Enable logging
stackabletech/opa-operator pull request #420
Opened 2023-02-22 10:46 UTC by maltesander

# Description

fixes https://github.com/stackabletech/opa-operator/issues/410

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2023-03-02 11:37 UTC, siegfriedweber requested changes
Some remarks and the changelog must be updated.

2023-03-06 08:55 UTC, maltesander commented on rust/crd/src/lib.rs
> +    pub vector_aggregator_config_map_name: Option<String>,
https://github.com/stackabletech/opa-operator/pull/420/commits/2edbb77697268031ca369de617ff3e55e66b8747 and tests & docs https://github.com/stackabletech/opa-operator/pull/420/commits/cbf6ccd1a1566416589f923b71b8abd18d705961

2023-03-06 08:58 UTC, maltesander commented on rust/operator-binary/src/controller.rs
> +    })?;
Good point: https://github.com/stackabletech/opa-operator/pull/420/commits/8dd397d5d67589077e148ba220dd1ff622aa7c7f

2023-03-06 09:55 UTC, maltesander commented on rust/operator-binary/src/controller.rs
> +    })
Done https://github.com/stackabletech/opa-operator/pull/420/commits/865d1b1ee6947fb011e7796798ef67405c23c745

2023-03-06 09:56 UTC, maltesander commented on rust/operator-binary/src/controller.rs
> +            "-x".to_string(),
Done https://github.com/stackabletech/opa-operator/pull/420/commits/8da3335f4edbc107fccd716c88bd22a64ac6dd06

2023-03-06 10:01 UTC, maltesander commented
test: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/opa-operator-it-custom/40/

2023-03-06 10:47 UTC, siegfriedweber approved these changes
LGTM

2023-03-06 10:48 UTC, maltesander commented
bors merge

2023-03-06 10:59 UTC, closed without merging