Upgrade vector
stackabletech/opa-operator pull request #465
Opened 2023-07-31 13:19 UTC by maltesander

# Description

WIP - just for issue reference

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [x] Changelog updated
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2023-08-01 15:45 UTC, siegfriedweber requested changes

2023-08-01 15:45 UTC, siegfriedweber commented on tests/templates/kuttl/logging/opa-vector-aggregator-values.yaml.j2
`filteredInvalidEvents` should be added and the `sinks` must be adapted:

```yaml
    filteredInvalidEvents:
      type: filter
      inputs: [vector]
      condition: |-
        .timestamp == from_unix_timestamp!(0) ||
        is_null(.level) ||
        is_null(.logger) ||
        is_null(.message)
  sinks:
    out:
      inputs: [filtered*]
{% if lookup('env', 'VECTOR_AGGREGATOR') %}
      type: vector
      address: {{ lookup('env', 'VECTOR_AGGREGATOR') }}
      buffer:
        # Avoid back pressure from VECTOR_AGGREGATOR. The test should
        # not fail if the aggregator is not available.
        when_full: drop_newest
{% else %}
      type: blackhole
{% endif %}
```

2023-08-02 07:35 UTC, maltesander commented on tests/templates/kuttl/logging/opa-vector-aggregator-values.yaml.j2
https://github.com/stackabletech/opa-operator/pull/465/commits/83651a6d46d7400562fd6f66a371be0082f94fe5

2023-08-02 12:45 UTC, siegfriedweber requested changes
LGTM but could you please also copy https://github.com/stackabletech/operator-templating/blob/main/template/tests/kuttl-test.yaml.jinja2 into this pull request?

2023-08-02 14:23 UTC, siegfriedweber approved these changes
LGTM

2023-08-03 07:05 UTC, merged