docs: Promote user-info-fetcher docs to navgation
stackabletech/opa-operator pull request #557
Opened 2024-04-26 06:19 UTC by sbernauer

# Description

Given that we are using it extensively already (e.g. in the e2e-security demo) and me handing out the link to multiple customers, I would like to promote https://docs.stackable.tech/home/nightly/opa/usage-guide/user-info-fetcher.html to include it in the navigation

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-04-26 07:59 UTC, Maleware submitted a review, later dismissed
LGTM! Thank you :)

2024-04-26 08:06 UTC, sbernauer commented
Giving @nightkr and @NickLarsenNZ a chance to comment...

2024-04-26 11:48 UTC, nightkr commented
Have we addressed the client API side yet? We shouldn't have been shipping it to demos _or_ customers before that, and the linked docs definitely don't.

2024-04-26 13:04 UTC, sbernauer commented
Are you talking about the API described in https://docs.stackable.tech/home/nightly/opa/usage-guide/user-info-fetcher.html#_user_info_fetcher_api?
Currently you can send an username or id and get all infos we can collect back. What exactly do you want to address, would you like to change the API?

2024-04-29 11:24 UTC, nightkr commented
The UIF provides the HTTP API, but we should wrap that in an OPA rule we provide, rather than have everyone hard-code the HTTP stuff themselves.

2024-04-30 07:51 UTC, fhennig commented
I don't think we have that yet. I agree that it would be good to have. Could we simply have a `uif` rego package that we deploy when the UIF is enabled? and users can import the package in their own code?

I think we can still do this 'promotion' here and do a follow-up PR to adress this. it's all in nightly anyways, but we need to prioritise the follow-up then

2024-05-02 09:22 UTC, sbernauer commented
Yeah, I can see the point of providing a regorule in addition to the HTTP API. The question is if we should block the docs on the API until the rego rules are there :thinking:

2024-05-02 10:24 UTC, nightkr commented
> I don't think we have that yet. I agree that it would be good to have. Could we simply have a uif rego package that we deploy when the UIF is enabled? and users can import the package in their own code?

Yes, basically this.

> Yeah, I can see the point of providing a regorule in addition to the HTTP API. The question is if we should block the docs on the API until the rego rules are there 🤔

We should, because the current HTTP API *is not public or stable*. The uif package is the stable API surface, the HTTP API is just an implementation detail for how to get there.

2024-05-02 12:40 UTC, fhennig submitted a review, later dismissed
blocked by #558

2024-05-22 06:38 UTC, sbernauer commented
I think the change is trivial and I would close this PR until everyone thinks we are ready to include the docs in the navigation

2024-07-23 07:47 UTC, sbernauer commented
Reopening according to the decision in the daily, as we where not able to ship https://github.com/stackabletech/opa-operator/issues/558 in time for the 23.07 release

2024-07-23 07:57 UTC, NickLarsenNZ submitted a review, later dismissed
LGTM

2024-07-23 08:01 UTC, Techassi requested changes
Some suggestions.

2024-07-23 08:01 UTC, Techassi commented on docs/modules/opa/pages/usage-guide/user-info-fetcher.adoc
> +This enables us e.g. to make breaking changes to the HTTP API while still keeping the rego rules API stable.
```suggestion
This enables us to make underlying (for example breaking) changes to the HTTP API while keeping the rego rules API stable.
```

2024-07-23 08:36 UTC, Techassi approved these changes

2024-07-23 08:39 UTC, merged